# Generated by Django 5.0.6 on 2026-07-08 08:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('size_mb', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('message', models.TextField(default='We are currently performing maintenance.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='Maximus', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_text', models.CharField(default='© Maximus. All rights reserved.', max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('adsense_code', models.TextField(blank=True)),
                ('enable_ads', models.BooleanField(default=False)),
                ('email_from', models.EmailField(default='noreply@maximus.dev', max_length=254)),
                ('purchase_email_subject', models.CharField(default='Your Download is Ready', max_length=200)),
                ('primary_color', models.CharField(default='#B5300A', max_length=7)),
                ('accent_color', models.CharField(default='#3ECF8E', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
