# Generated by Django 5.0.6 on 2026-07-19 06:31

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(max_length=45, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid IP address.', regex='^(\\d{1,3}\\.){3}\\d{1,3}$|^[0-9a-fA-F:]+$')])),
                ('reason', models.CharField(choices=[('honeypot', 'Honeypot hit'), ('rate_limit', 'Rate limit exceeded'), ('manual', 'Manual block'), ('brute_force', 'Brute force login')], max_length=20)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('blocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unblock_at', models.DateTimeField(blank=True, help_text='Null = permanent', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('honeypot', 'Honeypot triggered'), ('rate_limit', 'Rate limited'), ('brute_force', 'Brute force attempt'), ('suspicious', 'Suspicious pattern')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
