import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'Maximus Terms & Conditions — the rules governing your use of our platform.',
  alternates: { canonical: '/terms' },
}

export default function TermsPage() {
  return (
    <section className="bg-primary py-16 md:py-24">
      <div className="max-w-3xl mx-auto px-4 sm:px-6">
        <h1 className="text-3xl sm:text-4xl font-bold text-text-primary mb-4">Terms &amp; Conditions</h1>
        <p className="text-sm text-text-muted mb-10">Last updated: July 7, 2026</p>

        <div className="prose prose-gray max-w-none text-text-secondary text-[15px] leading-relaxed space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Maximus (&quot;the Platform&quot;), you agree to be bound by these Terms &amp; Conditions. If you do not agree, do not use the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">2. Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorised use.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">3. Use of the Platform</h2>
            <p>
              You may use the Platform only for lawful purposes and in accordance with these Terms. You agree not to:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Violate any applicable law or regulation.</li>
              <li>Transmit harmful, obscene, or infringing content.</li>
              <li>Attempt to gain unauthorised access to any part of the Platform.</li>
              <li>Interfere with or disrupt the Platform&apos;s infrastructure.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">4. Intellectual Property</h2>
            <p>
              All content, trademarks, and software on the Platform are the property of Maximus or its licensors. You are granted a limited, non-exclusive licence to use the Platform for its intended purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">5. AI-Generated Content</h2>
            <p>
              Content generated by Maximus AI tools is provided &quot;as is.&quot; You are solely responsible for reviewing and verifying any AI-generated output before use. Maximus does not guarantee the accuracy, completeness, or legality of generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">6. Subscriptions &amp; Payments</h2>
            <p>
              Paid plans are billed in advance on a recurring basis. You may cancel at any time; cancellation takes effect at the end of the current billing period. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Maximus shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">8. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Material changes will be communicated via the Platform or email. Continued use after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-text-primary mb-3">9. Contact</h2>
            <p>
              Questions about these Terms? <a href="/contact" className="text-secondary hover:underline">Contact us</a>.
            </p>
          </section>
        </div>
      </div>
    </section>
  )
}
