# Generated by Django 5.0.6 on 2026-07-15 17:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_purchase_email', models.BooleanField(default=True)),
                ('purchase_subject', models.CharField(default='Your Download is Ready', max_length=200)),
                ('purchase_template', models.TextField(default='Thank you for your purchase! Here is your download link: {{download_link}}')),
                ('email_provider', models.CharField(choices=[('console', 'Console (Development)'), ('smtp', 'SMTP'), ('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun')], default='console', max_length=50)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
